/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsBoardRouteImport } from './routes/boards.$board'
import { Route as ApiBoardsBoardNotesRouteImport } from './routes/api/boards.$board.notes'
import { Route as ApiBoardsBoardNotesIdRouteImport } from './routes/api/boards.$board.notes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardRoute = BoardsBoardRouteImport.update({
  id: '/boards/$board',
  path: '/boards/$board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsBoardNotesRoute = ApiBoardsBoardNotesRouteImport.update({
  id: '/api/boards/$board/notes',
  path: '/api/boards/$board/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsBoardNotesIdRoute = ApiBoardsBoardNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBoardsBoardNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/api/boards/$board/notes': typeof ApiBoardsBoardNotesRouteWithChildren
  '/api/boards/$board/notes/$id': typeof ApiBoardsBoardNotesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/api/boards/$board/notes': typeof ApiBoardsBoardNotesRouteWithChildren
  '/api/boards/$board/notes/$id': typeof ApiBoardsBoardNotesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/api/boards/$board/notes': typeof ApiBoardsBoardNotesRouteWithChildren
  '/api/boards/$board/notes/$id': typeof ApiBoardsBoardNotesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards/$board'
    | '/api/boards/$board/notes'
    | '/api/boards/$board/notes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards/$board'
    | '/api/boards/$board/notes'
    | '/api/boards/$board/notes/$id'
  id:
    | '__root__'
    | '/'
    | '/boards/$board'
    | '/api/boards/$board/notes'
    | '/api/boards/$board/notes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsBoardRoute: typeof BoardsBoardRoute
  ApiBoardsBoardNotesRoute: typeof ApiBoardsBoardNotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$board': {
      id: '/boards/$board'
      path: '/boards/$board'
      fullPath: '/boards/$board'
      preLoaderRoute: typeof BoardsBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/$board/notes': {
      id: '/api/boards/$board/notes'
      path: '/api/boards/$board/notes'
      fullPath: '/api/boards/$board/notes'
      preLoaderRoute: typeof ApiBoardsBoardNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/$board/notes/$id': {
      id: '/api/boards/$board/notes/$id'
      path: '/$id'
      fullPath: '/api/boards/$board/notes/$id'
      preLoaderRoute: typeof ApiBoardsBoardNotesIdRouteImport
      parentRoute: typeof ApiBoardsBoardNotesRoute
    }
  }
}

interface ApiBoardsBoardNotesRouteChildren {
  ApiBoardsBoardNotesIdRoute: typeof ApiBoardsBoardNotesIdRoute
}

const ApiBoardsBoardNotesRouteChildren: ApiBoardsBoardNotesRouteChildren = {
  ApiBoardsBoardNotesIdRoute: ApiBoardsBoardNotesIdRoute,
}

const ApiBoardsBoardNotesRouteWithChildren =
  ApiBoardsBoardNotesRoute._addFileChildren(ApiBoardsBoardNotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardRoute: BoardsBoardRoute,
  ApiBoardsBoardNotesRoute: ApiBoardsBoardNotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
