import antfu from '@antfu/eslint-config'
import { createSlopConfig } from 'eslint-plugin-slop'

export default antfu(
  {
    type: 'app',
    react: true,
    typescript: true,
    ignores: [
      '**/dist',
      '**/.celld',
      '**/routeTree.gen.ts',
      '**/wrangler.deploy.json',
      // Generated by the shadcn CLI; keep it diffable against upstream.
      '**/components/ui',
    ],
  },
  ...createSlopConfig({ cwd: import.meta.dirname }),
)
