import type { Linter } from 'eslint'
import { existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import antfu from '@antfu/eslint-config'
import { createSlopConfig } from 'eslint-plugin-slop'

const APPS_DIR = join(import.meta.dirname, 'apps')

/**
 * Root rules bind every app. An app may only add to them, through an optional
 * `apps/<name>/eslint.rules.ts` that default-exports flat config items.
 *
 * The file is deliberately not called eslint.config.ts: ESLint would then pick
 * it up as the nearest config inside the app and skip this one entirely.
 */
async function appExtensions(): Promise<Linter.Config[]> {
  const extensions: Linter.Config[] = []
  for (const app of readdirSync(APPS_DIR).sort()) {
    const file = join(APPS_DIR, app, 'eslint.rules.ts')
    if (!existsSync(file)) {
      continue
    }
    const { default: items } = await import(file) as { default: Linter.Config[] }
    for (const item of items) {
      for (const [rule, entry] of Object.entries(item.rules ?? {})) {
        const severity = Array.isArray(entry) ? entry[0] : entry
        if (severity === 'off' || severity === 0) {
          throw new Error(`apps/${app}/eslint.rules.ts turns off "${rule}". Apps may add or tighten rules, not disable root rules.`)
        }
      }
      // Scope to the app, so one app's rules never leak into another.
      const scoped = (glob: string): string => `apps/${app}/${glob}`
      extensions.push({
        ...item,
        files: (item.files ?? ['**/*']).flat().map(scoped),
        ...(item.ignores === undefined ? {} : { ignores: item.ignores.map(scoped) }),
      })
    }
  }
  return extensions
}

export default antfu(
  {
    type: 'app',
    react: true,
    typescript: true,
    ignores: [
      '**/dist',
      '**/.celld',
      '**/.wrangler',
      '**/wrangler.deploy.json',
      // Generated by the shadcn CLI; keep it diffable against upstream.
      '**/components/ui',
    ],
  },
  ...createSlopConfig({ cwd: import.meta.dirname }),
  ...await appExtensions(),
)
